### ISSUE TITLE
[Linting] Enforce indentation of chained operations

### ISSUE THREAD

**Issue by ycombinator** [elastic/eslint-config-kibana#5]
According to the [Kibana JS style guide](https://github.com/elastic/kibana/blob/master/style_guides/js_style_guide.md#chaining-operations):

> When using a chaining syntax, indent the subsequent chained operations.
>
> Also, if the chain is long, each method should be on a new line.
>
> ```
> // good
> $http.get('/info')
>   .then(({ data }) => this.transfromInfo(data))
>   .then((transformed) => $http.post('/new-info', transformed))
>   .then(({ data }) => console.log(data));
> 
> // bad
> $http.get('/info')
> .then(({ data }) => this.transfromInfo(data))
> .then((transformed) => $http.post('/new-info', transformed))
> .then(({ data }) => console.log(data));
> ``` 

Update the linting rules to enforce this.

**Comment by ycombinator** [comment]
I haven't tested it out but http://eslint.org/docs/rules/indent#memberexpression might help.

**Comment by kjbekkelund** [comment]
Moved to https://github.com/elastic/kibana/issues/13088
